### ISSUE TITLE
Cannot parse COMPANY_ECONOMY with OpenTTD 1.5.0

### ISSUE THREAD

**Issue by aidanmorgan** [sambol/node-libOpenttdAdmin#1]
Hi,

When attempting to poll for the COMPANY_ECONOMY data type, the following error is generated in node.

parsers.js:196
      .word64les('money')
       ^
TypeError: Object #<Object> has no method 'word64les'
    at Object.<anonymous> (C:\programming\projects\OpenTTD\Game\nodejs\parsers.js:196:8)
    at Object.self.into (C:\programming\projects\OpenTTD\Game\nodejs\node_modules\binary\index.js:258:12)
    at Object.module.exports.companyeconomy (C:\programming\projects\OpenTTD\Game\nodejs\parsers.js:193:16)
    at Object.<anonymous> (C:\programming\projects\OpenTTD\Game\nodejs\main.js:79:71)
    at Object.self.tap (C:\programming\projects\OpenTTD\Game\nodejs\node_modules\binary\index.js:248:12)
    at Socket.<anonymous> (C:\programming\projects\OpenTTD\Game\nodejs\main.js:60:10)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)

**Comment by sambol** [comment]
Hi, Please test
